x-deploy:
  host: deploy.thelio.local

services:
  docs:
    image: localhost:5000/flow-deploy-docs:${DEPLOY_TAG:-latest}
    volumes:
      - .:/app
      - ./site/nginx.dev.conf:/etc/nginx/conf.d/default.conf

  registry:
    image: registry:2
    ports:
      - "5000:5000"
    networks:
      - traefik

networks:
  traefik:
    external: true
